### ISSUE TITLE
BUG : skeletonBoneIgnored attribute depends on databinding order of execution

### ISSUE THREAD

**Issue by fbarthelery** [EudyContreras/Skeleton-Bones#16]
Thanks for creating this library. I just started to play with it and it looks promising. 

**Describe the bug**
When using attribute `skeletonBoneIgnored` the binding adapter method `setSkeletonIgnored()` looks for the parent skeleton drawable to store the ignored id by calling `getParentSkeletonDrawable()`. If the parent skeleton drawable is not found nothing happens and the view is not ignored.

There is no guaranteed order of execution in Android data binding as stated  [here](https://stackoverflow.com/questions/40932933/android-bindingadapter-order-of-execution). Thus the call to `setSkeletonIgnored()` can occurs before the call to `setSkeletonEnabled()` or other binding adapter methods who creates the skeleton drawable and the view won't be ignored.

**Expected behavior**
The view with `skeletonBoneIgnored="@{true}"` is ignored.

**Additional context**
Other binding adapter methods may be affected by this behavior. I think it also happens for `skeletonBoneHeight` ,`skeletonBoneMinHeight`

A workaround is to immediately create the `SkeletonDrawable ` programmatically  just after inflating the layout.

**Comment by EudyContreras** [comment]
@fbarthelery Thank you for bringing this up and for a great issue description. I will look into this soon 🙌

**Comment by EudyContreras** [comment]
@fbarthelery even though it is correct the that there is no guaranteed order of execution in Android data binding. This library should not suffer from this. I have not been able to reproduce the issue. would you mind sharing your set up and steps on how to reproduce.

**Comment by fbarthelery** [comment]
@EudyContreras  Here is a minimal sample project.
https://github.com/fbarthelery/Skeleton-bones-ordering-bug

**Comment by EudyContreras** [comment]
@fbarthelery Thank you for this I will look further into it and get back to you

**Comment by EudyContreras** [comment]
@fbarthelery this is now fixed with the new version 🎉
