### ISSUE TITLE
Question - How to change color?

### ISSUE THREAD

**Issue by phongbm** [EudyContreras/Skeleton-Bones#17]
Thank for library, but I have an issue.
I use this code in my fragment
```
skeletonBuilder = SkeletonDrawable.create(fragmentRootView)
                    .build()
                    .setEnabled(true)
                    .setAllowSavedState(true)
```
And this is result (image below)
My fragment has skeleton loading effect, but I want to change color green to gray?

Thanks.

![device-2021-01-11-150626](https://user-images.githubusercontent.com/7350399/104158035-14865780-541f-11eb-9b89-71f2973eeeb2.png)

**Comment by EudyContreras** [comment]
@phongbm Have you tried specifying a boneColorProperty ? in the readme I go through how to specify properties and how to build a bone drawable.

**Comment by phongbm** [comment]
I did it, thank you.
