### ISSUE TITLE
How to stop skeleton on views

### ISSUE THREAD

**Issue by TaQuangTu** [EudyContreras/Skeleton-Bones#19]
Thank for your great repository. I use your repo to create skeleton for screens in my app but how can i revert the screens to origin state after making them skeleton. Hope to hear your response. Sincerely, thank you.

**Comment by EudyContreras** [comment]
> Thank for your great repository. I use your repo to create skeleton for screens in my app but how can i revert the screens to origin state after making them skeleton. Hope to hear your response. Sincerely, thank you.

Hey @TaQuangTu The `app:skeletonEnabled` determines whether or not the skeleton is shown. It can be used with databinding for the best result. `app:skeletonEnabled="@{viewModel.loading}`
